### ISSUE TITLE
Online documentation

### ISSUE THREAD

**Issue by Boddlnagg** [contextfree/winrt-rust#14]
The AppVeyor build (see #13) can automatically run rustdoc (probably `cargo doc --no-deps` is best, because we don't want docs for winapi included) and upload the documentation to GitHub pages (`gh-pages` branch).

**Comment by Boddlnagg** [comment]
I just built a full documentation (`--features all`), it took a little over 10 minutes to build and resulted in about 300 MB of docs (the HTML version of the `gen.rs` source file is 65 MB alone).

I have no idea if that is going to be a problem.

**Comment by Boddlnagg** [comment]
This might not be needed now that https://docs.rs/ is a thing. We just need to make sure that documentation is built with `--features all`.

**Comment by Boddlnagg** [comment]
The documentation (without `--features all`) is available: https://docs.rs/winrt/*/x86_64-pc-windows-msvc/winrt/

I have added the link to `README.md` and `Cargo.toml`. Concerning the feature flag, see https://github.com/onur/docs.rs/issues/29

**Comment by Boddlnagg** [comment]
Passing `--features all` is now supported on docs.rs, and implemented in [a branch](https://github.com/Boddlnagg/winrt-rust/tree/docs). I want to wait for https://github.com/onur/docs.rs/issues/135 before landing this, however.

**Comment by frewsxcv** [comment]
Following up from the previous comment, here's an updated link: https://github.com/rust-lang/docs.rs/issues/135
