### ISSUE TITLE
Can we hide `ComPtr` from the public API?

### ISSUE THREAD

**Issue by Boddlnagg** [contextfree/winrt-rust#79]
This would mean that publicly visible types such as `IInspectable` would refer to what's currently `ComPtr<IInspectable>`.  Where we currently have references `&IInspectable`, we would then have effectively `&ComPtr<IInspectable>`, I don't know if that's a problem. The ABI representation is the same.

**Comment by Boddlnagg** [comment]
I have been doing some rather successful experiments in a branch: https://github.com/Boddlnagg/winrt-rust/tree/cleanup

**Comment by contextfree** [comment]
What's left to do to get that branch ready to be merged? Can you use any help?

**Comment by Boddlnagg** [comment]
The "problem" is that it's based on the 2018 edition branch (see https://github.com/contextfree/winrt-rust/pull/74) and I wanted to make a release with some other changes before merging that.

**Comment by Boddlnagg** [comment]
So I did release 0.6.0, merged the 2018 edition change, rebased this branch and opened a PR for it: #80

**Comment by contextfree** [comment]
Sweet, thanks! I'm trying this out on a Windows.UI.Composition sample I've been working on in case you want more testing/validation, though don't mean to suggest you should hold up merging whenever you think it's ready.
