### ISSUE TITLE
Using COM components?

### ISSUE THREAD

**Issue by paddyhoran** [contextfree/winrt-rust#81]
Is it possible to control applications that expose a COM API with this library?  I'm sorry if this is an obvious question.  

An example is probably best.  In Python I can do the following via `pywin32`:

```
    win32.pythoncom.CoInitialize()
    outlook = win32.Dispatch('outlook.application')
    mail = outlook.CreateItem(0)
    mail.To = 'some address'
    mail.Subject = 'Subject'
    mail.body = 'Body'
    mail.send
```

I know that WinRT is a different technology to COM but I'm wondering if there is interoperability to the point that this crate could be used for a use case like the above?

Thanks

**Comment by Boddlnagg** [comment]
Although one could reuse some internal components of winrt-rust to do such a thing (e.g. [BSTR](https://github.com/contextfree/winrt-rust/blob/master/src/bstr.rs), which doesn't actually belong in this crate, and [ComPtr](https://github.com/contextfree/winrt-rust/blob/master/src/comptr.rs)), those are implementation details and not meant to be used by consumers directly (and eventually even completely hidden from the public API).

The point of winrt-rust is the automatic wrapper code generation for WinRT based on WinRT metadata, and that is not available for plain COM.

You might have more luck with something like [com_rs](https://docs.rs/com-rs/0.2.0/com_rs/) or [wio-rs](https://github.com/retep998/wio-rs), which also provides a `ComPtr`.

**Comment by paddyhoran** [comment]
Ok, I thought so, thanks for the confirmation.
